//  protoc --go_out=plugins=grpc:. uniqURL_db.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.11.4
// source: uniqURL_db.proto

package grpc_client

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GetURL struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *GetURL) Reset() {
	*x = GetURL{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uniqURL_db_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetURL) ProtoMessage() {}

func (x *GetURL) ProtoReflect() protoreflect.Message {
	mi := &file_uniqURL_db_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetURL.ProtoReflect.Descriptor instead.
func (*GetURL) Descriptor() ([]byte, []int) {
	return file_uniqURL_db_proto_rawDescGZIP(), []int{0}
}

func (x *GetURL) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GetResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Depth  int32 `protobuf:"varint,1,opt,name=depth,proto3" json:"depth,omitempty"`
	Exists bool  `protobuf:"varint,2,opt,name=exists,proto3" json:"exists,omitempty"`
}

func (x *GetResult) Reset() {
	*x = GetResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uniqURL_db_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResult) ProtoMessage() {}

func (x *GetResult) ProtoReflect() protoreflect.Message {
	mi := &file_uniqURL_db_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResult.ProtoReflect.Descriptor instead.
func (*GetResult) Descriptor() ([]byte, []int) {
	return file_uniqURL_db_proto_rawDescGZIP(), []int{1}
}

func (x *GetResult) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *GetResult) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type SaveURL struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url   string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Depth int32  `protobuf:"varint,2,opt,name=depth,proto3" json:"depth,omitempty"`
}

func (x *SaveURL) Reset() {
	*x = SaveURL{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uniqURL_db_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveURL) ProtoMessage() {}

func (x *SaveURL) ProtoReflect() protoreflect.Message {
	mi := &file_uniqURL_db_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveURL.ProtoReflect.Descriptor instead.
func (*SaveURL) Descriptor() ([]byte, []int) {
	return file_uniqURL_db_proto_rawDescGZIP(), []int{2}
}

func (x *SaveURL) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *SaveURL) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

type Nothing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Nothing) Reset() {
	*x = Nothing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uniqURL_db_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Nothing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nothing) ProtoMessage() {}

func (x *Nothing) ProtoReflect() protoreflect.Message {
	mi := &file_uniqURL_db_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nothing.ProtoReflect.Descriptor instead.
func (*Nothing) Descriptor() ([]byte, []int) {
	return file_uniqURL_db_proto_rawDescGZIP(), []int{3}
}

var File_uniqURL_db_proto protoreflect.FileDescriptor

var file_uniqURL_db_proto_rawDesc = []byte{
	0x0a, 0x10, 0x75, 0x6e, 0x69, 0x71, 0x55, 0x52, 0x4c, 0x5f, 0x64, 0x62, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x75, 0x6e, 0x69, 0x71, 0x55, 0x52, 0x4c, 0x5f, 0x64, 0x62, 0x22, 0x1a,
	0x0a, 0x06, 0x67, 0x65, 0x74, 0x55, 0x52, 0x4c, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x39, 0x0a, 0x09, 0x67, 0x65,
	0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x65, 0x70, 0x74, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x64, 0x65, 0x70, 0x74, 0x68, 0x12, 0x16, 0x0a,
	0x06, 0x65, 0x78, 0x69, 0x73, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x65,
	0x78, 0x69, 0x73, 0x74, 0x73, 0x22, 0x31, 0x0a, 0x07, 0x73, 0x61, 0x76, 0x65, 0x55, 0x52, 0x4c,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75,
	0x72, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x65, 0x70, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x64, 0x65, 0x70, 0x74, 0x68, 0x22, 0x09, 0x0a, 0x07, 0x6e, 0x6f, 0x74, 0x68,
	0x69, 0x6e, 0x67, 0x32, 0x70, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x73, 0x65, 0x64, 0x12, 0x32, 0x0a,
	0x03, 0x67, 0x65, 0x74, 0x12, 0x12, 0x2e, 0x75, 0x6e, 0x69, 0x71, 0x55, 0x52, 0x4c, 0x5f, 0x64,
	0x62, 0x2e, 0x67, 0x65, 0x74, 0x55, 0x52, 0x4c, 0x1a, 0x15, 0x2e, 0x75, 0x6e, 0x69, 0x71, 0x55,
	0x52, 0x4c, 0x5f, 0x64, 0x62, 0x2e, 0x67, 0x65, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22,
	0x00, 0x12, 0x32, 0x0a, 0x04, 0x73, 0x61, 0x76, 0x65, 0x12, 0x13, 0x2e, 0x75, 0x6e, 0x69, 0x71,
	0x55, 0x52, 0x4c, 0x5f, 0x64, 0x62, 0x2e, 0x73, 0x61, 0x76, 0x65, 0x55, 0x52, 0x4c, 0x1a, 0x13,
	0x2e, 0x75, 0x6e, 0x69, 0x71, 0x55, 0x52, 0x4c, 0x5f, 0x64, 0x62, 0x2e, 0x6e, 0x6f, 0x74, 0x68,
	0x69, 0x6e, 0x67, 0x22, 0x00, 0x42, 0x0e, 0x5a, 0x0c, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_uniqURL_db_proto_rawDescOnce sync.Once
	file_uniqURL_db_proto_rawDescData = file_uniqURL_db_proto_rawDesc
)

func file_uniqURL_db_proto_rawDescGZIP() []byte {
	file_uniqURL_db_proto_rawDescOnce.Do(func() {
		file_uniqURL_db_proto_rawDescData = protoimpl.X.CompressGZIP(file_uniqURL_db_proto_rawDescData)
	})
	return file_uniqURL_db_proto_rawDescData
}

var file_uniqURL_db_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_uniqURL_db_proto_goTypes = []interface{}{
	(*GetURL)(nil),    // 0: uniqURL_db.getURL
	(*GetResult)(nil), // 1: uniqURL_db.getResult
	(*SaveURL)(nil),   // 2: uniqURL_db.saveURL
	(*Nothing)(nil),   // 3: uniqURL_db.nothing
}
var file_uniqURL_db_proto_depIdxs = []int32{
	0, // 0: uniqURL_db.parsed.get:input_type -> uniqURL_db.getURL
	2, // 1: uniqURL_db.parsed.save:input_type -> uniqURL_db.saveURL
	1, // 2: uniqURL_db.parsed.get:output_type -> uniqURL_db.getResult
	3, // 3: uniqURL_db.parsed.save:output_type -> uniqURL_db.nothing
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_uniqURL_db_proto_init() }
func file_uniqURL_db_proto_init() {
	if File_uniqURL_db_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_uniqURL_db_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetURL); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uniqURL_db_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uniqURL_db_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveURL); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uniqURL_db_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Nothing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_uniqURL_db_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_uniqURL_db_proto_goTypes,
		DependencyIndexes: file_uniqURL_db_proto_depIdxs,
		MessageInfos:      file_uniqURL_db_proto_msgTypes,
	}.Build()
	File_uniqURL_db_proto = out.File
	file_uniqURL_db_proto_rawDesc = nil
	file_uniqURL_db_proto_goTypes = nil
	file_uniqURL_db_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ParsedClient is the client API for Parsed service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ParsedClient interface {
	Get(ctx context.Context, in *GetURL, opts ...grpc.CallOption) (*GetResult, error)
	Save(ctx context.Context, in *SaveURL, opts ...grpc.CallOption) (*Nothing, error)
}

type parsedClient struct {
	cc grpc.ClientConnInterface
}

func NewParsedClient(cc grpc.ClientConnInterface) ParsedClient {
	return &parsedClient{cc}
}

func (c *parsedClient) Get(ctx context.Context, in *GetURL, opts ...grpc.CallOption) (*GetResult, error) {
	out := new(GetResult)
	err := c.cc.Invoke(ctx, "/uniqURL_db.parsed/get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parsedClient) Save(ctx context.Context, in *SaveURL, opts ...grpc.CallOption) (*Nothing, error) {
	out := new(Nothing)
	err := c.cc.Invoke(ctx, "/uniqURL_db.parsed/save", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ParsedServer is the server API for Parsed service.
type ParsedServer interface {
	Get(context.Context, *GetURL) (*GetResult, error)
	Save(context.Context, *SaveURL) (*Nothing, error)
}

// UnimplementedParsedServer can be embedded to have forward compatible implementations.
type UnimplementedParsedServer struct {
}

func (*UnimplementedParsedServer) Get(context.Context, *GetURL) (*GetResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedParsedServer) Save(context.Context, *SaveURL) (*Nothing, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Save not implemented")
}

func RegisterParsedServer(s *grpc.Server, srv ParsedServer) {
	s.RegisterService(&_Parsed_serviceDesc, srv)
}

func _Parsed_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetURL)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParsedServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/uniqURL_db.parsed/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParsedServer).Get(ctx, req.(*GetURL))
	}
	return interceptor(ctx, in, info, handler)
}

func _Parsed_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveURL)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParsedServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/uniqURL_db.parsed/Save",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParsedServer).Save(ctx, req.(*SaveURL))
	}
	return interceptor(ctx, in, info, handler)
}

var _Parsed_serviceDesc = grpc.ServiceDesc{
	ServiceName: "uniqURL_db.parsed",
	HandlerType: (*ParsedServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "get",
			Handler:    _Parsed_Get_Handler,
		},
		{
			MethodName: "save",
			Handler:    _Parsed_Save_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "uniqURL_db.proto",
}
